# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qx_DByIDwcybRkHalgGp-1ZcUuc1W1si
"""

!pip install ase

from ase import Atoms
from ase.visualize.plot import plot_atoms
from itertools import combinations
import matplotlib.pyplot as plt


symbols = ['C'] * 6 + ['H'] * 6
positions = [
    [-4.460019861,  1.184794043,  0.000000000],
    [-3.068577805,  1.261072426,  0.000000000],
    [-2.306807662,  0.093639345,  0.000000000],
    [-2.936616961, -1.149108769,  0.000000000],
    [-4.328104412, -1.225541428,  0.000000000],
    [-5.089861221, -0.058108576,  0.000000000],
    [-1.218662089,  0.153277758,  0.000000000],
    [-2.575604573,  2.232865284,  0.000000000],
    [-5.055611884,  2.097663349,  0.000000000],
    [-2.341295512, -2.062134138,  0.000000000],
    [-4.821091200, -2.197334806,  0.000000000],
    [-6.178055920, -0.117627788,  0.000000000]
]


benzene = Atoms(symbols=symbols, positions=positions)


print("Distancias C–C (en Å):")
carbon_indices = [i for i, s in enumerate(symbols) if s == 'C']
for i, j in combinations(carbon_indices, 2):
    dist = benzene.get_distance(i, j)
    if dist < 1.7:  # solo enlaces C–C
        print(f"C{i+1}–C{j+1}: {dist:.3f} Å")


fig, ax = plt.subplots(figsize=(6, 6))
plot_atoms(benzene, ax, radii=0.5, rotation=('0x,0y,0z'), show_unit_cell=0)
plt.title("Molécula de Benceno (C6H6)")
plt.axis('off')
plt.tight_layout()
plt.show()